#!/bin/bash

# SPDX-FileCopyrightText: 2023 - 2025 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

set -Eeuo pipefail

ROOT="$(dirname "${0}")"

source "${ROOT}"/globals

# Build TTF files using Iosevka
build_iosevka() {
  if [[ "${IOSEVKA}" = "HEAD" ]]; then
    git clone --depth 1 https://github.com/be5invis/Iosevka.git iosevka
  else
    git clone --depth 1 --branch "${IOSEVKA}" https://github.com/be5invis/Iosevka.git iosevka
  fi
  pushd iosevka > /dev/null
  cp "${ROOT}"/src/jambo-mono_complete.toml private-build-plans.toml
  git apply "${ROOT}"/src/4-yBar_tweak.patch
  npm install
  npm run build -- contents::"${VARIANT}"
  popd > /dev/null
}

# Apply Nerd Fonts patches to TTF files to create *-nerd veriants.
patch_nerd_fonts() {
  local n
  local i
  local dir
  local font

  mkdir -p font-patcher
  pushd font-patcher > /dev/null
  if [[ "${NERDFONT}" = "latest" ]]; then
    wget https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FontPatcher.zip
  else
    wget https://github.com/ryanoasis/nerd-fonts/releases/download/"${NERDFONT}"/FontPatcher.zip
  fi
  unzip FontPatcher.zip
  n="$(nproc)"
  i=0
  for dir in ../iosevka/dist/"${VARIANT}"/{TTF,TTF-Unhinted}; do
    mkdir -p "${dir}-Nerd"
    for font in "${dir}"/*.ttf; do
      show_info "Patching ${font@Q}..."
      fontforge -script font-patcher "${font}" -out "${dir}-Nerd" --careful -c -l -q > /dev/null 2>&1 &
      i=$((i + 1))
      if [ $((i % n)) -eq 0 ]; then
        i=0
        wait
      fi
    done
    wait
  done
  popd > /dev/null
}

# Re-arrange and rename files.
copy_rename_files() {
  local dir
  local file
  local newfile
  local destdir

  for dir in iosevka/dist/"${VARIANT}"/{TTF,TTF-Unhinted,WOFF2,WOFF2-Unhinted}; do
    pushd "${dir}" > /dev/null
    destdir="${DEST}/${VARIANT}/$(basename "${dir,,}")"
    mkdir -p "${destdir}"
    for file in *; do
      newfile="$(echo "${file}" |
                tr '[:upper:]' '[:lower:]' |
                sed -e "s/-normal/-/g" \
                    -e "s/-\././g" \
                    -e "s/^${VARIANT}\./${VARIANT}-regular./g")"
      if [ -n "${newfile}" ]; then
        cp -v "${file}" "${destdir}/${newfile}"
      else
        cp -v "${file}" "${destdir}/${file}"
      fi
    done
    popd > /dev/null
  done
  for dir in iosevka/dist/"${VARIANT}"/{TTF-Nerd,TTF-Unhinted-Nerd}; do
    pushd "${dir}" > /dev/null
    destdir="${DEST}/${VARIANT}/$(basename "${dir,,}")"
    mkdir -p "${destdir}"
    for file in *Nerd*; do
      newfile="$(echo "${file}" |
                tr '[:upper:]' '[:lower:]' |
                sed -e "s/jambo mono/jambo-mono-nerd/g" \
                    -e "s/\ nerd font complete//g" \
                    -e "s/nerd /nerd-/g" \
                    -e "s/jambomononerdfont/jambo-mono-nerd/g" \
                    -e "s/ //g")"
      if [ -n "${newfile}" ]; then
        cp -v "${file}" "${destdir}/${newfile}"
      else
        cp -v "${file}" "${destdir}/${file}"
      fi
    done
    popd > /dev/null
  done
}

! check_command git npm ttfautohint fontforge wget && exit 3

ROOT="$(readlink -f "$(dirname "${0}")")"
DEST="${ROOT}"/dest
IOSEVKA=v33.3.4
NERDFONT=v3.4.0
# IOSEVKA=HEAD
# NERDFONT=latest
BUILD=$(mktemp -d)
VARIANT=jambo-mono # alternative: jambo-mono-tall

trap 'rm -rf "${BUILD}"; exit' EXIT INT TERM ERR

pushd "${BUILD}" > /dev/null

build_iosevka
patch_nerd_fonts
copy_rename_files

sync

popd > /dev/null
