#! /bin/bash
set -Eeuo pipefail

# Colored prompt for error messages.
show_error() {
  echo -e $'\033[1;31m'"$*"$'\033[0m' 1>&2
}
export -f show_error

# Check if list of command-line programs are in the PATH.
check_command() {
  local package
  local missing=()
  for package in "${@}"; do
    if ! command -v "${package}" >/dev/null; then
      missing+=("${package}")
    fi
  done
  if [ ${#missing[@]} -eq 0 ]; then
    return 0
  else
    show_error "MISSING: ${missing[*]@Q} not installed."
    return 1
  fi
}
export -f check_command

# Build TTF files using Iosevka
build_iosevka() {
  git clone --depth 1 --branch "${IOSEVKA}" https://github.com/be5invis/Iosevka.git iosevka
  pushd iosevka >/dev/null
  cp "${ROOT}"/src/jambo-mono_complete.toml private-build-plans.toml
  git apply "${ROOT}"/src/4-yBar_tweak.patch
  npm install
  npm run build -- contents::"${VARIANT}"
  popd >/dev/null
}

# Apply Nerd Fonts patches to TTF files to create *-nerd veriants.
patch_nerd_fonts() {
  mkdir -p font-patcher
  pushd font-patcher >/dev/null
  wget https://github.com/ryanoasis/nerd-fonts/releases/download/"${NERDFONT}"/FontPatcher.zip
  unzip FontPatcher.zip
  N="$(nproc)"
  I=0
  for DIR in ../iosevka/dist/"${VARIANT}"/{ttf,ttf-unhinted}; do
    mkdir -p "${DIR}-nerd"
    for FONT in "${DIR}"/*.ttf; do
      echo "Patching ${FONT@Q}..."
      fontforge -script font-patcher "${FONT}" -out "${DIR}-nerd" --careful -c -l -q >/dev/null 2>&1 &
      I=$((I + 1))
      if [ $((I % N)) -eq 0 ]; then
        I=0
        wait
      fi
    done
    wait
  done
  popd >/dev/null
}

# Re-arrange and rename files.
rename_nerd_ttf() {
  for DIR in iosevka/dist/"${VARIANT}"/{ttf-nerd,ttf-unhinted-nerd}; do
    pushd "${DIR}" >/dev/null
    for FILE in *Nerd*; do
      NEWFILE="$(echo "${FILE}" |
                tr '[:upper:]' '[:lower:]' |
                sed -e "s/jambo mono/jambo-mono-nerd/g" \
                    -e "s/\ nerd font complete//g" \
                    -e "s/nerd /nerd-/g" \
                    -e "s/jambomononerdfont/jambo-mono-nerd/g" \
                    -e "s/ //g")"
      mv "${FILE}" "${NEWFILE}"
    done
    popd >/dev/null
  done
}

! check_command git npm ttfautohint fontforge wget && exit 3

ROOT="$(readlink -f "$(dirname "${0}")")"
DEST="${ROOT}"/dest
IOSEVKA=v24.1.0
NERDFONT=v3.0.1
BUILD=$(mktemp -d)
VARIANT=jambo-mono # alternative: jambo-mono-tall

trap 'rm -rf "${BUILD}"; exit' EXIT INT TERM

pushd "${BUILD}" >/dev/null

build_iosevka
patch_nerd_fonts
rename_nerd_ttf

# Move final files to "${DEST}" directory.
mv iosevka/dist/"${VARIANT}" "${DEST}"
sync

popd >/dev/null
