#! /bin/bash
set -eu

if [ "${EUID}" -eq 0 ]; then
  mkdir -p /usr/local/share/fonts/jambo
  cp -Ra {ttf,ttf-unhinted} /usr/local/share/fonts/jambo
else
  mkdir -p "${HOME}/.local/share/fonts/jambo"
  cp -Ra {ttf,ttf-unhinted} "${HOME}/.local/share/fonts/jambo"
fi
