#! /bin/bash
set -eu

if [ "${EUID}" -eq 0 ]; then
  if [ -d /usr/local/share/fonts/jambo ]; then
    rm -rv /usr/local/share/fonts/jambo
  fi
else
  if [ -d "${HOME}"/.local/share/fonts/jambo ]; then
    rm -rv "${HOME}"/.local/share/fonts/jambo
  fi
fi
