# SPDX-FileCopyrightText: 2023 sudorook <daemon@nullcodon.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program. If not, see <https://www.gnu.org/licenses/>.

[buildPlans.jambo-mono-tall]
family = "Jambo Mono"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.jambo-mono-tall.variants]
  inherits = "ss12"

    [buildPlans.jambo-mono-tall.variants.design]
    capital-k = "straight-serifless"
    f = "serifless-crossbar-at-x-height"
    i = "serifed-flat-tailed"
    j = "flat-hook-serifed"
    k = "straight-serifless"
    t = "flat-hook"
    zero = "slashed"
    six = "closed-contour"
    # seven = "bend-crossbar"
    eight = "crossing"
    nine = "closed-contour"
    brace = "curly"
    dollar = "through"
    cent = "through"

[buildPlans.jambo-mono-tall.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.jambo-mono-tall.metricOverride]
symbolMid = 295 # 340
cap = 710 # 735
ascender = 745 # 735
leading = 1210 # 1250
xHeight = 530 # 520
parenSize = 1016 # 966

[buildPlans.jambo-mono]
family = "Jambo Mono"
spacing = "normal"
serifs = "sans"
noCvSs = false
exportGlyphNames = true

  [buildPlans.jambo-mono.variants]
  inherits = "ss12"

    [buildPlans.jambo-mono.variants.design]
    capital-k = "straight-serifless"
    f = "serifless-crossbar-at-x-height"
    i = "serifed-flat-tailed"
    j = "flat-hook-serifed"
    k = "straight-serifless"
    t = "flat-hook"
    zero = "slashed"
    six = "closed-contour"
    # seven = "bend-crossbar"
    eight = "crossing"
    nine = "closed-contour"
    brace = "curly"
    dollar = "through"
    cent = "through"

[buildPlans.jambo-mono.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.jambo-mono.metricOverride]
symbolMid = 295 # 340
cap = 700 # 735
ascender = 735 # 735
leading = 1210 # 1250
xHeight = 530 # 520
parenSize = 916 # 966
